services:
  postgresql:
    image: postgres:11
    container_name: postgresql
    environment:
      POSTGRES_USER: "postgres_user"
      POSTGRES_PASSWORD: "postgres_password"
      POSTGRES_DB: "postgres_db"
    networks:
      - network
  user_code:
    build:
      context: .
      dockerfile: ./dockerfiles/user_code.Dockerfile
    container_name: user_code
    image: user_code_image
    restart: always
    environment:
      DAGSTER_POSTGRES_USER: "postgres_user"
      DAGSTER_POSTGRES_PASSWORD: "postgres_password"
      DAGSTER_POSTGRES_DB: "postgres_db"
      DAGSTER_CURRENT_IMAGE: "user_code_image"
    networks:
      - network
  webserver:
    build:
      context: .
      dockerfile: ./dockerfiles/dagster.Dockerfile
    entrypoint:
      - dagster-webserver
      - -h
      - "0.0.0.0"
      - -p
      - "3000"
      - -w
      - workspace.yaml
    container_name: webserver
    expose:
      - "3000"
    ports:
      - "3000:3000"
    environment:
      DAGSTER_POSTGRES_USER: "postgres_user"
      DAGSTER_POSTGRES_PASSWORD: "postgres_password"
      DAGSTER_POSTGRES_DB: "postgres_db"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /tmp/io_manager_storage:/tmp/io_manager_storage
      - ./workspace.yaml:/opt/dagster/dagster_home/workspace.yaml
      - ./dagster.yaml:/opt/dagster/dagster_home/dagster.yaml
    networks:
      - network
    depends_on:
      - postgresql
      - user_code
  daemon:
    build:
      context: .
      dockerfile: ./dockerfiles/dagster.Dockerfile
    entrypoint:
      - dagster-daemon
      - run
    container_name: daemon
    restart: on-failure
    environment:
      DAGSTER_POSTGRES_USER: "postgres_user"
      DAGSTER_POSTGRES_PASSWORD: "postgres_password"
      DAGSTER_POSTGRES_DB: "postgres_db"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /tmp/io_manager_storage:/tmp/io_manager_storage
      - ./workspace.yaml:/opt/dagster/dagster_home/workspace.yaml
      - ./dagster.yaml:/opt/dagster/dagster_home/dagster.yaml
    networks:
      - network
    depends_on:
      - postgresql
      - user_code

networks:
  network:
    driver: bridge
    name: network