x-dagster-volumes: &dagster-volumes
  - /tmp/io_manager_storage
  - ./workspace.yaml:/opt/dagster/dagster_home/workspace.yaml
  - ./dagster.yaml:/opt/dagster/dagster_home/dagster.yaml
x-dagster-postgres-env: &dagster-postgres-env
  DAGSTER_POSTGRES_USER: "postgres_user"
  DAGSTER_POSTGRES_PASSWORD: "postgres_password"
  DAGSTER_POSTGRES_DB: "postgres_db"

services:
  minio:
    ports:
      - 9000:9000
      - 9001:9001
    container_name: minio
    volumes:
      - ./minio-data:/data
    environment:
      - MINIO_ROOT_USER=ROOTNAME
      - MINIO_ROOT_PASSWORD=CHANGEME123
    image: quay.io/minio/minio:RELEASE.2024-05-10T01-41-38Z
    command: server /data --console-address ":9001"

  postgresql:
    image: arm64v8/postgres:11.22-alpine
    environment:
      POSTGRES_USER: "postgres_user"
      POSTGRES_PASSWORD: "postgres_password"
      POSTGRES_DB: "postgres_db"
    volumes:
      - ./pg-data:/var/lib/postgresql/data
      - ./docker-entrypoint-initdb.d/:/docker-entrypoint-initdb.d
    networks:
      - network

  user_code:
    image: niits/usercode:latest
    restart: always
    environment:
      TPBANK_ACCOUNT_NUMBER: $TPBANK_ACCOUNT_NUMBER
      TPBANK_PASSWORD: $TPBANK_PASSWORD
      TPBANK_DEVICE_ID: $TPBANK_DEVICE_ID
      DATABASE_DSN: postgresql://postgres_user:postgres_password@localhost:5432/postgres_db
      <<: *dagster-postgres-env
    networks:
      - network

  webserver:
    image: niits/dagster:latest
    entrypoint:
      - dagster-webserver
      - -h
      - "0.0.0.0"
      - -p
      - "3000"
      - -w
      - workspace.yaml
    expose:
      - "3000"
    ports:
      - "3000:3000"
    environment: *dagster-postgres-env
    volumes: *dagster-volumes
    networks:
      - network
    depends_on:
      - postgresql
      - user_code

  daemon:
    image: niits/dagster:latest
    entrypoint:
      - dagster-daemon
      - run
    restart: on-failure
    environment: *dagster-postgres-env
    volumes: *dagster-volumes
    networks:
      - network
    depends_on:
      - postgresql
      - user_code

  adminer:
    image: adminer
    ports:
      - 8080:8080
    networks:
      - network

networks:
  network:
    driver: bridge
    name: network
