name: Build Docker Image for Dagster Daemon and Web Server

on:
  push:
    branches: [ "main" ]
jobs:
  rebuilt:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: docker/setup-qemu-action@v3
    - uses: docker/setup-buildx-action@v3
    - uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_HUB_USERNAME }}
        password: ${{ secrets.DOCKER_HUB_PASSWORD }}
    - uses: docker/build-push-action@v5
      with:
        context: .
        file: dockerfiles/dagster.Dockerfile
        platforms: linux/amd64,linux/arm64
        push: true
        cache-from: type=registry,ref=${{ secrets.DOCKER_HUB_USERNAME }}/dagster:latest
        cache-to: type=inline
        tags: |
          ${{ secrets.DOCKER_HUB_USERNAME }}/dagster:latest
