name: Update containers

on:
  workflow_run:
    workflows: ["Build Docker images"]
    branches: [main]
    types:
      - completed
jobs:
  update-docker-container:
    runs-on: ubuntu-latest
    steps:
      - name: Tailscale
        uses: tailscale/github-action@v2
        with:
          oauth-client-id: ${{ secrets.TS_OAUTH_CLIENT_ID }}
          oauth-secret: ${{ secrets.TS_OAUTH_SECRET }}
          tags: tag:ci
      - name: SSH into Raspberry Pi
        env:
          SERVER_COMPOSE_DIR: ${{ secrets.SERVER_COMPOSE_DIR }}
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USERNAME}}
          key: ${{ secrets.SERVER_SSH_KEY }}
          envs: SERVER_COMPOSE_DIR
          script: |
            docker pull ${{ secrets.DOCKER_HUB_USERNAME }}/usercode:latest && \
                docker pull ${{ secrets.DOCKER_HUB_USERNAME }}/dagster:latest && \
                docker compose -f ${{ secrets.SERVER_COMPOSE_DIR }}/docker-compose.yaml up -d
